// Clean intermediate build artifacts and caches.
// Usage: node scripts/clean.js

const fs = require("node:fs");
const path = require("node:path");

const rootDir = path.join(__dirname, "..");

const dirsToClean = [
  path.join(rootDir, "build"),            // Intermediate build artifacts
  path.join(rootDir, "dist"),             // Distribution output
  path.join(rootDir, "src-tauri", "target"),  // Rust compilation cache
  path.join(rootDir, "node_modules"),     // npm dependencies
];

const filesToClean = [
  path.join(rootDir, "web", "lucide-icons.js"), // Auto-generated by beforeBuildCommand
];

for (const dir of dirsToClean) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
    console.log(`Cleaned: ${path.relative(rootDir, dir)}`);
  }
}

for (const file of filesToClean) {
  if (fs.existsSync(file)) {
    fs.unlinkSync(file);
    console.log(`Cleaned: ${path.relative(rootDir, file)}`);
  }
}

console.log("Clean complete.");
