// Pre-build asset preparation — single entry point for all auto-generated resources.
// Run automatically via beforeBuildCommand or manually: node scripts/prepare-assets.js
const path = require("node:path");
const fs = require("node:fs");
const { execSync } = require("node:child_process");

const root = path.join(__dirname, "..");
const assetsDir = path.join(root, "assets");
const iconsDir = path.join(root, "src-tauri", "icons");
const webDir = path.join(root, "web");

// ---------------------------------------------------------------------------
// 1. App bundle icons (tauri icon)
// ---------------------------------------------------------------------------
const sourceIcon = path.join(assetsDir, "icon.png");
const destIcon = path.join(iconsDir, "icon.png");

if (!fs.existsSync(sourceIcon)) {
  console.error("assets/icon.png not found — skipping icon generation");
} else if (
  !fs.existsSync(destIcon) ||
  fs.statSync(sourceIcon).mtime > fs.statSync(destIcon).mtime
) {
  console.log("Generating platform icons from assets/icon.png …");
  execSync(`npx tauri icon "${sourceIcon}" -o "${iconsDir}"`, {
    cwd: root,
    stdio: "inherit",
  });
  console.log("Platform icons generated");
}

// ---------------------------------------------------------------------------
// 2. Web icon (displayed in settings.html)
// ---------------------------------------------------------------------------
const webIcon = path.join(webDir, "icon.png");
copyIfChanged(sourceIcon, webIcon, "web icon");

// ---------------------------------------------------------------------------
// 3. Tray icons
// ---------------------------------------------------------------------------
for (const name of ["trayTemplate.png", "trayTemplate@2x.png", "trayIcon.ico"]) {
  const src = path.join(assetsDir, name);
  const dest = path.join(iconsDir, name);
  if (fs.existsSync(src)) {
    copyIfChanged(src, dest, name);
  }
}

// ---------------------------------------------------------------------------
// 4. Lucide UI icons
// ---------------------------------------------------------------------------
generateLucideIcons();

// ===========================================================================
// Helpers
// ===========================================================================

function copyIfChanged(src, dest, label) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  if (
    !fs.existsSync(dest) ||
    fs.statSync(src).mtime > fs.statSync(dest).mtime
  ) {
    fs.copyFileSync(src, dest);
    console.log(`Copied ${label}: ${src} → ${dest}`);
  }
}

function generateLucideIcons() {
  const lucide = require(path.join(
    root,
    "node_modules",
    "lucide",
    "dist",
    "cjs",
    "lucide.js",
  ));

  const ICONS = [
    "Home",
    "Keyboard",
    "Settings2",
    "ShieldCheck",
    "Cloud",
    "SlidersHorizontal",
    "FileCode2",
    "BookOpen",
    "Info",
    "Sun",
    "Moon",
    "Monitor",
    "Eye",
    "EyeOff",
    "RefreshCw",
    "X",
    "CircleDot",
    "Sparkles",
    "Copy",
    "Trash2",
    "CalendarDays",
    "Mic",
    "Timer",
    "ChevronDown",
  ];

  const attrs = {
    xmlns: "http://www.w3.org/2000/svg",
    width: "24",
    height: "24",
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    "stroke-width": "2",
    "stroke-linecap": "round",
    "stroke-linejoin": "round",
  };

  function toSvgString(elements) {
    const inner = elements
      .map(([tag, a]) => {
        const pairs = Object.entries(a)
          .map(([k, v]) => `${k}="${v}"`)
          .join(" ");
        return `<${tag} ${pairs}/>`;
      })
      .join("");
    const attrStr = Object.entries(attrs)
      .map(([k, v]) => `${k}="${v}"`)
      .join(" ");
    return `<svg ${attrStr}>${inner}</svg>`;
  }

  const entries = [];
  for (const name of ICONS) {
    const iconData = lucide[name];
    if (!iconData) {
      console.warn(`Icon not found: ${name}`);
      continue;
    }
    const kebab = name
      .replace(/([A-Z])/g, (m, p, i) => (i ? "-" : "") + p.toLowerCase())
      .replace(/(\d+)/g, "-$1");
    entries.push(`  "${kebab}": '${toSvgString(iconData)}'`);
  }

  const output = `// Auto-generated by scripts/prepare-assets.js — do not edit\nwindow.LucideIcons = {\n${entries.join(",\n")}\n};\n`;

  const outPath = path.join(webDir, "lucide-icons.js");
  if (fs.existsSync(outPath) && fs.readFileSync(outPath, "utf-8") === output) {
    return; // unchanged
  }
  fs.writeFileSync(outPath, output, "utf-8");
  console.log(`Generated ${entries.length} Lucide icons to ${outPath}`);
}
